---
title: "World Health Data Application"
description: |
  This application explores the trends of world health data made for FIT5147: Data Exploration and Visualisation
author:
  - name: Vinny Vu 
    url: https://www.linkedin.com/in/vinny-vu-809bb1139/
date: 11-16-2020
output:
  distill::distill_article:
    self_contained: false
bibliography: references.bib  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```



In today's it is common belief that we are becoming increasingly unhealthy because of the move in diets towards convenient often unhealthy foods and increased inactivity @physical-inactivity. To assess this statement we will be looking into the following health factors, height, body mass index, blood pressure and cholesterol and their changes across time. 

It is common belief that due to the better access to quality food, nutrients and wealth humans are growing taller over time and therefore it is of interest to analysis the changes in height data. 

Per the World Health Organization @BP Hypertension or raised blood pressure is the condition in which the blood vessels have persistently raised pressure and the higher the pressure, the harder the heart must pump. Hypertension is a serious medical condition and can increase the risk of heart, brain, kidney, and other diseases being one of the major causes of premature deaths worldwide. Therefore, it is of interest to assess the trends of raised blood pressure data. 

Body mass index or BMI for short, is a measure for indicating nutritional status in adults defined as a person's weight in kilograms divided by the square of the person's height in meters (kg/m2) @BMI. BMI was developed as a risk indicator of diseases, the higher the BMI is often resulted in a higher level of excessive body fat resulting the increased risk of some diseases such as premature death, cardiovascular diseases, blood pressure, osteoarthritis, some cancers and diabetes @BMI. Therefore, it is of interest to assess the trends in BMI levels. 

Per betterhealth @Chol Cholesterol is defined as a type of fat that is part of all animal cells that is essential for many of the body's metabolic processes, including the production of hormones, bile and vitamin D. Specifically Low-density lipoprotein (LDL) cholesterol, carries most of the cholesterol that is delivered to cells and is often referred to as "bad" cholesterol as when its level in the bloodstream is high, it can clog up your arteries. High cholesterol leads to fatty deposits developing in the arteries which causes the vessel to narrow eventually becoming blocked leading to heart disease and stroke. Therefore, it is of interest to assess the trends in LDL cholesterol levels.

Specifically we will be analyzing world health data to answer the following questions:
      
* What is the trend in the world health data across time and what are the specific trends for each country (BMI, Height, Blood Pressure and Cholesterol)?
* Is there a relationship between BMI and other health factors (Height, Blood Pressure and Cholesterol) and what is it?
* Do countries within the same continent or with similar cultures share similar results and trends and what are these results/trends?


Links to the Application can be found [here](https://vinny-vu.shinyapps.io/Application/)